# Nettoyage des donn√©es

In [ ]:
# Formatage date
from pyspark.sql import functions as F

df_spark = df_spark.withColumn('date', F.date_format(F.to_timestamp(df_spark['date'], 'yyyy-MM-dd\'T\'HH:mm:ss.SSSXXX'), 'yyyy-MM-dd HH:mm'))
df_spark = df_spark.orderBy(F.desc('date'))
df_spark.show(2)

NameError: name 'df_spark' is not defined